### ISSUE TITLE
Define the current versions in composer.json

### ISSUE THREAD

**Issue by peter279k** [ace411/fauxton-client#4]
Taking a look at the branch `v1.0.0`. Consider the `require` block in `composer.json`:
https://github.com/ace411/fauxton-client/blob/7cf38c7728c1f2ed324c46abe16a197d2f1ab117/composer.json#L17

This `require` block should be changed into following sample `require` block.

```json
...
"require": {
        "php": ">=7.0",
        "ext-curl": "*",
        "chemem/bingo-functional": "^1.10",
        "jakub-onderka/php-console-color": "^0.1",
        "react/event-loop": "^1"  
    },...
```
What do you think about this?

**Comment by ace411** [comment]
The v1.0.0 branch is not yet complete. Once all the features have been implemented and all the code tested - I will release a production-ready version of the fauxton-client.

**Comment by peter279k** [comment]
If having any issues or features need to help, feel free to create them!

**Comment by ace411** [comment]
Yeah, like the console and support for IBM Cloudant.
